project:
  type: website

website: 
  favicon: input/favicon.png
  twitter-card: 
    creator: "@baarthur0"
  open-graph: 
    locale: pt-BR
    site-name: "Arthur Bazolli"

profile:
  default: english
  group: [english, portuguese]
  
comments:
  giscus:
    repo: baarthur/baarthur.github.io