project:
  title: "Arthur Bazolli Alvarenga"
  output-dir: ./docs/

website:
  navbar:
    background: primary
    right:
      - href: ../pt
        text: Português
      - href: ../
        text: English
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - href: input/cv.pdf
        text: CV

lang: en

format:
  html:
    theme: 
     light: [flatly, styles.scss] 
     dark: [darkly, styles.scss]
    css: styles.css
    toc: true
    mainfont: Atkinson Hyperlegible