project:
  type: website
  output-dir: docs

website:
  title: "Arthur Bazolli Alvarenga"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    mainfont: Atkinson Hyperlegible



