---
title: "Untitled"
format: html
draft: true
---

```{r}
#| label: setup

library(here)
```


Primeiro vc cria os dados normalmente nesse chunk. com `eval: false`, ele não vai ser avaliado na hora de renderizar.
```{r}
#| label: gerar-dados
#| eval: false

df <- # aqui seu código mega pesado
```

E aqui começamos nosso mandrake: vc vai criar um chunk invisível para salvar os dados! Além de `eval: false`, usamos `include: false` para que ele não seja exibido no arquivo final.
```{r}
#| label: salvar-dados
#| eval: false
#| include: false

# salvar

## opção 1: RDS. bom demais, pau pra toda obra. vc pode salvar o que quiser
data %>% saveRDS(here("data/df.RDS"))

## opção 2: fst. é o mais eficiente, mas só serve pra salvar dataframe.
data %>% fst::write_fst(here("data/df.fst"))
```

Por fim, um segundo código que tb não é incluído, mas precisa ser avaliado. 
```{r}
#| label: ler-dados
#| include: false
#| eval: false

# carregue e seja feliz!
df <- readRDS(here("data/df.RDS"))

## ou
df <- read_fst(here("data/df.fst"))
```
